mm_stats-$(CONFIG_HONOR_MEM_REPORT) := mem_report.o
mm_stats-$(CONFIG_HONOR_MEM_DETECT) += mem_detect.o
mm_stats-y += mem_stats_sysfs.o
obj-$(CONFIG_HONOR_MEM_STATS) += mm_stats.o
obj-$(CONFIG_HONOR_MEMLOCK_STATS) += memlock_stats/
obj-$(CONFIG_DEBUG_PAGE_LOCK) += page_lock/
